const Form = require('../Models/form');
const { Resend } = require('resend');

// Make sure to add RESEND_API_KEY to your .env file
const resend = new Resend(process.env.RESEND_API_KEY);

const submitForm = async (req, res, next) => {
    try {
        const { fullName, emailAddress, phoneNumber, businessName, serviceInterestedIn, message } = req.body;

        if (!fullName || !emailAddress || !phoneNumber || !serviceInterestedIn || !message) {
            return res.status(400).json({ error: "Please provide all required fields." });
        }

        const newForm = await Form.create({
            fullName,
            emailAddress,
            phoneNumber,
            businessName,
            serviceInterestedIn,
            message
        });

        const emailHtml = `
            <div style="font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background-color:#e9f9f0; padding:24px; color:#0b3d2e;">
              <div style="max-width:600px; margin:0 auto; background:#ffffff; border-radius:12px; overflow:hidden; box-shadow:0 12px 30px rgba(0,0,0,0.08);">
                <div style="background: linear-gradient(135deg, #1e7f4e 0%, #3ac17b 100%); padding:20px; text-align:center;">
                  <h1 style="margin:0; font-size:22px; font-weight:700; color:#ffffff; letter-spacing:0.6px;">New Website Form Submission</h1>
                </div>
                <div style="padding:24px;">
                  <p style="margin:0 0 16px; font-size:16px; color:#1c3f33;">A new submission has been received via the website contact form. Details are below:</p>
                  <hr style="border:none; border-top:1px solid rgba(0,0,0,0.08); margin:16px 0;" />
                  <table width="100%" cellpadding="0" cellspacing="0" style="font-size:15px; color:#1c3f33;">
                    <tr>
                      <td style="padding:8px 0; font-weight:600; width:40%;">Full Name</td>
                      <td style="padding:8px 0;">${fullName}</td>
                    </tr>
                    <tr>
                      <td style="padding:8px 0; font-weight:600;">Email Address</td>
                      <td style="padding:8px 0;">${emailAddress}</td>
                    </tr>
                    <tr>
                      <td style="padding:8px 0; font-weight:600;">Phone Number</td>
                      <td style="padding:8px 0;">${phoneNumber}</td>
                    </tr>
                    <tr>
                      <td style="padding:8px 0; font-weight:600;">Business Name</td>
                      <td style="padding:8px 0;">${businessName || 'N/A'}</td>
                    </tr>
                    <tr>
                      <td style="padding:8px 0; font-weight:600;">Service Interested In</td>
                      <td style="padding:8px 0;">${serviceInterestedIn}</td>
                    </tr>
                    <tr>
                      <td style="padding:8px 0; font-weight:600; vertical-align:top;">Message</td>
                      <td style="padding:8px 0; white-space:pre-line;">${message}</td>
                    </tr>
                  </table>
                  <div style="margin-top:24px; font-size:13px; color:#556b63;">
                    <p style="margin:0;">This email was automatically generated by your website form. Reply to the sender to follow up.</p>
                  </div>
                </div>
              </div>
            </div>
        `;

        // It is recommended to verify a custom domain in Resend and replace onboarding@resend.dev
        await resend.emails.send({
            from: 'HFF <no_reply@halalfoodfoundation.org.uk>', 
            to: 'info@halalfoodfoundation.co.uk',
            subject: 'Contact Form Submission',
            html: emailHtml,
            reply_to: emailAddress
        });

        return res.status(201).json({ message: "Form submitted successfully.", data: newForm });
    } catch (error) {
        next(error);
    }
};

module.exports = { submitForm };
